- name: Remove problematic sources list
  file:
    path: /etc/apt/sources.list.d/backports.list
    state: absent

- name: Ensure correct repositories in sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{ item }}"
    create: yes
    backup: yes
  loop:
    - "deb http://deb.debian.org/debian bullseye main contrib non-free"
    - "deb http://deb.debian.org/debian-security/ bullseye-security main contrib non-free"
    - "deb http://deb.debian.org/debian bullseye-updates main contrib non-free"
  ignore_errors: yes

- name: Remove any existing backports repository
  lineinfile:
    path: /etc/apt/sources.list
    regexp: ".*bullseye-backports.*"
    state: absent

- name: update apt cache
  apt:
    update_cache: yes
    allow_unauthenticated: yes
    
- name: install packages
  apt:
    name:
      - curl
      - vim
      - unzip
      - git
      - python3
      - python3-pip
      - htop
      - net-tools
      - jq
    state: present
    update_cache: yes

- name: install docker
  apt:
    name: docker.io
    state: present

- name: Create developer user
  user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    groups: docker,sudo
    append: yes
    create_home: yes

- name: Allow user to use sudo without password
  lineinfile:
    dest: /etc/sudoers.d/{{ dev_user }}
    line: "{{ dev_user }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    mode: '0440'

- name: Ensure .ssh directory exists for user
  file:
    path: "/home/{{ dev_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: copy authorized_keys
  authorized_key:
    user: "{{ dev_user }}"
    key: "{{ lookup('file', role_path + '/files/id_ed25519.pub') }}"

- name: up docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install developer Python tools
  pip:
    name:
     - virtualenv
     - ansible
     - requests

- name: clean apt cache
  apt:
    autoclean: yes
    autoremove: yes
